# Generated by Django 4.1.7 on 2023-03-29 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_procuct_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripition',
            new_name='description',
        ),
    ]
